# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'URLEmbeddedViewSample' do
pod 'URLEmbeddedView', :path => '../'
pod 'NoticeObserveKit', '0.4.0'
pod 'MisterFusion', '3.0.0'
end
