# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'URLEmbeddedViewSample' do
pod 'URLEmbeddedView', :path => '../'
pod 'NoticeObserveKit', '0.3.0'
pod 'MisterFusion', '2.2.1'
end
